GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjY5OTU5MjUyfQ.BPjyX4_KReK0IvvSE0Bsl5hpwtrjDsPhA7FKLB3aOFc
###

GET http://localhost:3000/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmFodWwiLCJnZW5kZXIiOiJNYWxlIiwibG9jYXRpb24iOiJoeWRlcmFiYWQiLCJpYXQiOjE2MTc0MzI0MDd9.Eqevw5QE70ZAVrmOZUc6pflUbeI0ffZUmQLDHYplU8g


###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}
####
GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmFodWwiLCJnZW5kZXIiOiJNYWxlIiwibG9jYXRpb24iOiJoeWRlcmFiYWQiLCJpYXQiOjE2MTc0MzI0MDd9.Eqevw5QE70ZAVrmOZUc6pflUbeI0ffZUmQLDHYplU8g
